FROM ubuntu

RUN apt-get update && \
     apt-get install -y net-tools && \
     apt-get install -y iputils-ping
#RUN echo "78 1 27 1" | DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y ubuntu-server