version: "3.8"


services:

  router1:
    build: 
      context: ./router1
      dockerfile: dockerFile
    container_name: router1
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
    # - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv4.tcp_timestamps=0
    command: >-
      sh -c "sysctl -p &&
      iptables -t nat -A POSTROUTING -j MASQUERADE &&
      tail -f /dev/null"
    volumes:
      - "./router1/sysctl.conf:/etc/sysctl.conf"
    networks:
      host-bridge:
      vlan-1:
        ipv4_address: 10.0.0.10

  router2:
    build: 
      context: ./router1
      dockerfile: dockerFile
    container_name: router2
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.tcp_timestamps=0
    command: >-
      sh -c "sysctl -p &&
      iptables -t nat -A POSTROUTING -j MASQUERADE &&
      tail -f /dev/null"
    volumes:
      - "./router1/sysctl.conf:/etc/sysctl.conf"
    depends_on:
      - router1
    networks:
      vlan-1:
        ipv4_address: 10.0.0.2
      vlan-2:
        ipv4_address: 10.0.1.2

  dhcp1:
    build: 
      context: ./dhcp_server
      dockerfile: dockerFile
    user: root
    container_name: dhcpd1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    restart: on-failure
    command: ["sleep","infinity"] 
    tty: true
    privileged: true
    ports:
      - "67:67/udp"
    volumes:
      - ./dhcp_server/rndc.key:/etc/dhcp/rndc.key
      - ./dhcp_server/bash.sh:/bash.sh
      - ./dhcp_server/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./dhcp_server/isc-dhcp-server:/etc/default/isc-dhcp-server
      - ./dhcp_server/interfaces:/etc/network/interfaces
      - ./dhcp_server/rndc.conf:/etc/dhcp/rndc.conf
    cap_add:
      - NET_ADMIN
    environment:
      - HTTP_USER=foo
      - HTTP_PASS=bar
    networks:
      vlan-1:
        ipv4_address: 10.0.0.4
  
  dns:
    build: 
      context: ./dns
      dockerfile: dockerFile
    user: root
    container_name: dns
    volumes:
      - ./dns/rndc.key:/etc/dhcp/rndc.key
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/bash.sh:/bash.sh
      #- ./dns/resolv.conf:/etc/systemd/resolv.conf
      - ./dns/resolved.conf:/etc/systemd/resolved.conf
      - ./dns/bind/named.conf.local:/etc/bind/named.conf.local
      - ./dns/bind/named.conf.options:/etc/bind/named.conf.options
      - ./dns/rndc.conf:/etc/dhcp/rndc.conf
      
      #
      - ./dns/bind/db.google:/etc/bind/zones/db.google
      - ./dns/bind/db.lan01:/etc/bind/zones/db.lan01
      - ./dns/bind/db.lan02:/etc/bind/zones/db.lan02

    restart: on-failure
    command: ["sleep","infinity"]
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      - HTTP_USER=foo
      - HTTP_PASS=bar
    networks:
      vlan-1:
        ipv4_address: 10.0.0.3

  nginx-proxy:
    build: 
      context: ./reverse_proxy
      dockerfile: dockerFile
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./reverse_proxy/hosts:/etc/hosts
      - ./reverse_proxy/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./reverse_proxy/includes/:/etc/nginx/includes/
      - ./reverse_proxy/ssl/:/etc/ssl/certs/nginx/
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    privileged: true
    networks:
      vlan-1:
        ipv4_address: 10.0.0.20
      vlan-2:

  web_server_1:
    build: 
      context: ./web_server1
      dockerfile: dockerFile
    container_name: web_server_1
    expose:
      - "80"
    volumes:
      - ./html/:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: http://www.google.com/web1
    restart: always

    networks:
      vlan-1:
        ipv4_address: 10.0.0.21
  

  web_server_2:
    build: 
      context: ./web_server2
      dockerfile: dockerFile
    container_name: web_server_2
    expose:
      - "80"
    volumes:
      - ./html2/:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: http://www.google.com/web2
    restart: always

    networks:
      vlan-2:
        ipv4_address: 10.0.1.21



  openvpn:
    container_name: VPN
    restart: always
    cap_add:
      - NET_ADMIN
    build: 
      context: ./openvpn
      dockerfile: dockerFile
    ports:
      - "8443:8443/tcp" #router 1 debe enrutar a este puerto
    networks:
      vlan-2: 
        ipv4_address: 10.0.1.10
    volumes:
     - ./openvpn/conf:/etc/openvpn
  

  cliente_01:
    build: 
      context: ./ubuntu
      dockerfile: dockerFile
    container_name: ubuntu
    privileged: true
    restart: on-failure
    command: >-
      sh -c "ip route replace default via 10.0.0.10 &&
      tail -f /dev/null"
    volumes:
      - ./ubuntu/resolv.conf:/etc/resolv.conf
      - ./ubuntu/interfaces:/etc/network/interfaces
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - router1
      - dhcp1
    networks:
      vlan-1:

  cliente_02:
    build: 
      context: ./ubuntu
      dockerfile: dockerFile
    container_name: ubuntu2
    privileged: true
    restart: on-failure
    command: >-
      sh -c "ip route replace default via 10.0.1.2 &&
      tail -f /dev/null"
    volumes:
      - ./ubuntu/resolv.conf:/etc/resolv.conf
      - ./ubuntu/interfaces:/etc/network/interfaces
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - router2
    networks:
      vlan-2:

networks:
  host-bridge:
    name: Host bridge
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      driver: default
  vlan-1:
    name: LAN Virtual 1
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  vlan-2:
    name: LAN Virtual 2
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24