version: "3.8"


services:

  cliente_01:
    build: 
      context: ./ubuntu
      dockerfile: dockerFile
    container_name: ubuntu
    restart: on-failure
    command: ["sleep","infinity"]
    networks:
      - vlan-1

  dhcp1:
    build: 
      context: ./dhcp_server
      dockerfile: dockerFile
    container_name: dhcp1
    volumes:
      - ./dhcp_server/config/:/data/
    networks:
      vlan-1:
        ipv4_address: 10.0.0.4
  
  dns:
    build: 
      context: ./dns
      dockerfile: dockerFile
    container_name: dns
    volumes:
      - ./dns/conf/:/etc/bind
    restart: on-failure
    command: ["sleep","infinity"]
    networks:
      vlan-1:
        ipv4_address: 10.0.0.3

  nginx-proxy:
    build: 
      context: ./reverse_proxy
      dockerfile: dockerFile
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
    networks:
      vlan-1:
        ipv4_address: 10.0.0.20

  web_server_1:
    build: 
      context: ./web_server
      dockerfile: dockerFile
    container_name: web_server_1
    expose:
      - "80"
    volumes:
      - ./html/:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: http://www.google.com/web1
    restart: always
    
    networks:
      vlan-1:
        ipv4_address: 10.0.0.21

  openvpn:
    container_name: VPN
    restart: always
    cap_add:
      - NET_ADMIN
    build: 
      context: ./openvpn
      dockerfile: dockerFile
    ports:
      - "8443:8443/tcp" #router 1 debe enrutar a este puerto
    networks:
      vlan-2: 
        ipv4_address: 10.0.1.10
    volumes:
     - ./openvpn/conf:/etc/openvpn
  router1:
    build: 
      context: ./router1
      dockerfile: dockerFile
    container_name: router1
    restart: on-failure

networks:
  vlan-1:
    name: LAN Virtual 1
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.0.0.0/24"
          ip_range: "10.0.0.0/24"
          gateway: "10.0.0.1"
  
  vlan-2:
    name: LAN Virtual 2
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.0.1.0/24"
          ip_range: "10.0.1.0/24"
          gateway: "10.0.1.1"




