FROM ubuntu

#instalar el servidor bind
RUN apt-get update && \
     apt-get install -y bind9 bind9utils bind9-doc


#RUN apt-get install -y dnsutils

#RUN /etc/init.d/bind9 restart

#RUN chmod +rwx /etc/resolv.conf
#RUN echo "nameserver 10.0.0.3" > /etc/resolv.conf



# Copiar la configuracion del archivo hacia el contenedor
#RUN cp -v /dns/named.conf.options /etc/bind/named.conf.options
