FROM ubuntu

# Install the dhcpd server.
RUN apt update &&\
     apt-get install -y init &&\
     apt-get install -y network-manager &&\
     apt-get install systemd &&\
     apt-get install -y iproute2 &&\
     apt-get install -y net-tools && \
     apt-get install -y iputils-ping && \
     apt-get install -yqq daemonize dbus-user-session fontconfig &&\
     apt install -y isc-dhcp-server

#CMD systemctl start isc-dhcp-server